export const dailyPrompts = [
    // Morning & Intention Setting
    "Today, I choose to feel...",
    "My main priority for today is...",
    "I am looking forward to...",
    "One thing I can do to make today great is...",
    "Today, I will be kind to myself by...",
    "If I could only accomplish three things today, they would be...",
    "I am grateful to wake up because...",
    "What is the energy I want to bring into this room today?",
    "Today, I will let go of the need to...",
    "My daily affirmation is...",

    // Evening & Reflection
    "The best part of today was...",
    "Something I learned today was...",
    "I felt most like myself when...",
    "One thing I could have done differently is...",
    "Did I act in alignment with my values today?",
    "I am proud of myself for...",
    "A moment of stillness I found today was...",
    "What was the biggest challenge I faced today?",
    "How did I take care of my body today?",
    "Tomorrow, I want to focus more on...",

    // Emotional Awareness
    "Right now, my heart feels...",
    "If my current mood was a weather forecast, it would be...",
    "I feel anxious about... because...",
    "What does my inner child need to hear right now?",
    "I feel most at peace when...",
    "The emotion I am trying to avoid is...",
    "What is draining my energy right now?",
    "What is filling my energy right now?",
    "I feel strongest when I...",
    "I forgive myself for...",

    // Gratitude & Positivity
    "Three small things that made me smile today:",
    "I am lucky to have [Person's Name] in my life because...",
    "A privilege I often overlook is...",
    "I appreciate my body because...",
    "The most delicious thing I tasted recently was...",
    "I am grateful for the technology to...",
    "A happy memory that never fails to cheer me up is...",
    "Something beautiful I saw outside was...",
    "I am grateful for my ability to...",
    "Thank you, past self, for...",

    // Self-Discovery & Identity
    "Who am I when no one is watching?",
    "What is a core value I will never compromise on?",
    "If money were no object, I would spend my days...",
    "What is a belief I used to hold that I have changed my mind about?",
    "My favorite quality about myself is...",
    "When do I lose track of time?",
    "What does \"success\" actually look like to me?",
    "If I could talk to my teenage self, I would say...",
    "A skill I have always wanted to master is...",
    "What makes me feel truly alive?",

    // Relationships & Connection
    "A relationship I want to invest more time in is...",
    "I feel most loved when...",
    "A boundary I need to set is...",
    "What is a conversation I’ve been avoiding?",
    "The qualities I value most in a friend are...",
    "How can I be a better listener?",
    "Someone who inspires me is...",
    "I feel misunderstood when...",
    "An act of kindness I witnessed or received was...",
    "Who brings out the best in me?",

    // Dealing with Hard Times
    "This too shall pass. Right now, I just need to...",
    "What is the smallest step I can take to improve this situation?",
    "I am allowed to feel...",
    "What is this challenge trying to teach me?",
    "Who can I reach out to for support?",
    "I have survived hard days before by...",
    "Being \"strong\" right now means...",
    "What lies is my anxiety telling me?",
    "What is the truth that counters those lies?",
    "I give myself permission to rest because...",

    // Future & Goals
    "In one year, I hope to be...",
    "A habit I want to break is...",
    "A habit I want to build is...",
    "What is stopping me from starting [Goal]?",
    "My dream home feels like...",
    "If I knew I couldn't fail, I would...",
    "Five years from now, will this worry matter?",
    "What is one thing I can do today to help my future self?",
    "My ideal morning routine looks like...",
    "Where do I want to travel next?",

    // Creativity & Fun
    "If I wrote a book, the title would be...",
    "My perfect fictional world to live in would be...",
    "If I could have dinner with anyone (dead or alive), it would be...",
    "The song that best describes my life right now is...",
    "If I had a superpower, it would be...",
    "Describe the color blue to someone who has never seen it.",
    "Write a letter to the Universe.",
    "If animals could talk, which one would be the rudest?",
    "Describe your perfect day from start to finish.",
    "Make a list of things that smell good.",

    // Quick Lists
    "5 things I need to get off my chest.",
    "10 things that make me happy.",
    "3 things I am good at.",
    "The top 5 songs on my playlist right now.",
    "5 places I want to visit.",
    "3 things that are stressing me out.",
    "10 things I would buy with $1,000.",
    "5 books/movies that changed my perspective.",
    "3 compliments I can give myself.",
    "1 word to describe today.",

    // Daily Wins
    "What is a small victory you had today?",
    "What is one thing you crossed off your to-do list?",
    "What was the best decision you made today?",
    "What is a compliment you received (or gave yourself)?",
    "What is a problem you solved today?",
    "What is something you did just for you today?",
    "What is a moment where you felt proud of yourself?",
    "What is something new you tried today?",
    "What is a distraction you successfully avoided?",
    "What is something you handled better than you thought you would?",

    // Vibe Check
    "What is one word that describes your mood right now?",
    "What is the dominant emotion you felt today?",
    "On a scale of 1-10, what is your energy level?",
    "What is something that drained your battery today?",
    "What is something that recharged your battery today?",
    "What is the color of your day today?",
    "What is a stressor you can let go of right now?",
    "What is something that made you feel calm?",
    "What is a song that matches your energy today?",
    "What does your body need right now (water, sleep, movement)?",

    // Little Details
    "What is the most delicious thing you ate or drank?",
    "What is something funny you saw or heard?",
    "What is a piece of good news you heard today?",
    "What is something beautiful you noticed outside?",
    "What is a quote or phrase that stuck with you today?",
    "What is the best conversation you had today?",
    "What is something you are grateful for right this second?",
    "What is a sound you heard that you enjoyed?",
    "What is something unexpected that happened?",
    "What is the weather like, and how did it affect you?",

    // Tough Stuff
    "What is the hardest part of today?",
    "What is a mistake you made (and what did you learn)?",
    "What is something you are worried about for tomorrow?",
    "What is a boundary you struggled to keep?",
    "What is something you wish you hadn't said or done?",
    "What is a recurring thought you had today?",
    "What is the \"frog\" you had to eat today?",
    "What is something you need help with?",
    "What is an emotion you tried to suppress today?",
    "What is one thing you can forgive yourself for?",

    // Looking Forward
    "What is your main focus for tomorrow?",
    "What is one thing you are excited about?",
    "What is an outfit you want to wear tomorrow?",
    "What is the first thing you want to do when you wake up?",
    "Who is someone you want to connect with soon?",
    "What is a goal you want to make progress on this week?",
    "What is a healthy meal you want to eat tomorrow?",
    "What is a risk you want to take?",
    "What is something you need to prepare tonight for tomorrow?",
    "What is your intention for tomorrow in one sentence?",

    // Random & Fun
    "What is a movie or show episode you watched today?",
    "What is a weird thought you had?",
    "If today was a chapter in a book, what is the title?",
    "What is a meme or video that made you laugh?",
    "What is something you Googled today?",
    "What is the screen time notification saying today?",
    "What is a texture you felt today?",
    "What is a smell you encountered today?",
    "If you could redo one hour of today, which one would it be?",
    "What is a wish you have right now?",

    // Deep Dive
    "What is a truth you realized today?",
    "What is a way you showed kindness?",
    "What is something you took for granted today?",
    "What is a habit you are trying to build?",
    "What is something that challenged your patience?",
    "What is a memory that popped into your head?",
    "What is something you are \"waiting\" for?",
    "What is the most important thing in your life right now?",
    "What is a fear that held you back today?",
    "What is a way you were authentic today?"
];
